

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import ConfigureAmplifyClientSide from "./components/ConfigureAmplifyClientSide";
import { SessionProvider } from "./components/SessionProvider";
import { getUserClientPoolId } from "./utils/getClientId";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  const headersList = headers()
  const host = headersList.get('x-pathname');

  console.log("path layout", host);

  const userPoolClientId = await getUserClientPoolId(host!);

  console.log("poolId clientside", userPoolClientId)

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {userPoolClientId}
          <ConfigureAmplifyClientSide
            userPoolCLientId={userPoolClientId}
          />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
